#!/usr/bin/env ansible-playbook

- name: run tasks
  hosts: vagrant
  tasks:

    - name: apt install locales
      when: 'ansible_pkg_mgr == "apt"'
      become: yes
      apt:
        name: locales

    - name: yum install glibc-common
      when: 'ansible_pkg_mgr == "yum"'
      become: yes
      yum:
        name: glibc-common

    - name: dnf install glibc-common
      when: 'ansible_pkg_mgr == "dnf"'
      become: yes
      dnf:
        name:
         - glibc-common
         - langpacks-en
         - glibc-locale-source

    - name: locale
      command: locale

    - name: which localedef
      command: which localedef

    - name: localedef
      become: yes
      command: localedef --inputfile en_US --charmap UTF-8 en_US.UTF-8

    - name: update-locale
      become: yes
      command: update-locale LC_ALL=en_US.UTF-8
      when: 'ansible_pkg_mgr == "apt"'

    - name: locale
      command: locale

